services:
  db:
    image: postgres:17
    container_name: ${COMPOSE_PROJECT_NAME:-cronicorn}-db
    restart: ${DB_RESTART:-unless-stopped}
    networks: [cronicorn]
    ports:
      - "${DB_PORT:-6666}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  migrator:
    profiles: [dev, prod]
    build:
      context: .
      dockerfile: Dockerfile.migrator
      target: migrator
    container_name: ${COMPOSE_PROJECT_NAME:-cronicorn}-migrator
    restart: no
    networks: [cronicorn]
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Override DATABASE_URL to use container hostname (local .env uses localhost:6666)
      DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@${COMPOSE_PROJECT_NAME:-cronicorn}-db:5432/${POSTGRES_DB:-db}

  api:
    profiles: [prod]
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ${COMPOSE_PROJECT_NAME:-cronicorn}-api
    restart: unless-stopped
    networks: [cronicorn]
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@${COMPOSE_PROJECT_NAME:-cronicorn}-db:5432/${POSTGRES_DB:-db}
      PORT: ${PORT:-3333}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      WEB_URL: ${WEB_URL}
      API_URL: ${API_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "${PORT:-3333}:3333"

  scheduler:
    profiles: [prod]
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: ${COMPOSE_PROJECT_NAME:-cronicorn}-scheduler
    restart: unless-stopped
    networks: [cronicorn]
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_MODEL: ${AI_MODEL}
      NODE_ENV: ${NODE_ENV:-production}

volumes:
  db_data:

networks:
  cronicorn:
    driver: bridge
