version: "3"

services:
  cronicorn-dev-db:
    container_name: cronicorn-dev-db
    image: postgres:17
    restart: always
    ports:
      - 6666:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - cronicorndevdatavolume:/var/lib/postgresql/data

volumes:
  cronicorndevdatavolume: