services:
  db:
    image: postgres:17
    container_name: ${COMPOSE_PROJECT_NAME:-cronicorn}-db
    restart: ${DB_RESTART:-unless-stopped}
    networks: [cronicorn]
    ports:
      - "${DB_PORT:-6666}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  cronicorn:
    driver: bridge