name: Release Test

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Simple test
        run: |
          echo "Release triggered: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Release URL: ${{ github.event.release.html_url }}"
