name: Tag Test

on:
  push:
    tags:
      - "v*"
      - "v*.*.*"
  create:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Simple test
        run: |
          echo "Tag triggered: ${{ github.ref }}"
          echo "Tag name: ${{ github.ref_name }}"
